# Generated by Django 6.1.1 on 2026-09-19 04:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('perimeter', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('incident_count', models.PositiveIntegerField()),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], default='low', max_length=20)),
                ('last_computed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WildlifeSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('Elephas maximus', 'Asian Elephant'), ('Panthera tigris', 'Bengal Tiger'), ('Panthera pardus', 'Indian Leopard'), ('Bos gaurus', 'Gaur')], max_length=100)),
                ('common_name', models.CharField(blank=True, max_length=100)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('source', models.CharField(default='iNaturalist', max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('quality_grade', models.CharField(default='research', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['species'], name='wildlife_wi_species_4049d3_idx'), models.Index(fields=['observed_at'], name='wildlife_wi_observe_75a62f_idx')],
            },
        ),
    ]
